language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE prueba;"
  - mysql -u root -e "CREATE USER 'prueba'@'localhost' IDENTIFIED BY 'prueba';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON prueba.* TO 'prueba'@'localhost';"

after_success:
  - mvn clean cobertura:cobertura coveralls:report
